name: Build surgio image and publish to dockerhub

on: 
  release:
    types: [published]
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - docker-entrypoint.sh
      - .github/workflows/main.yml
      - requirements.txt
  workflow_dispatch:
  schedule:
    - cron: 0 0 */15 * 5

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Docker Image
    steps:
      -
        name: Checkout
        uses: actions/checkout@master

      -
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: |
            linux/amd64
            linux/arm64/v8
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/surgio:latest
